import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  try {
    const { topic } = await request.json();

    if (!topic) {
      return NextResponse.json(
        { error: "Missing topic field" },
        { status: 400 }
      );
    }

    // Try to generate image using Pollinations.ai
    try {
      const prompt = `Create a beautiful, high-quality background image related to the topic: "${topic}". The image should be visually appealing, professional, and suitable as a background for a quiz application. Style: modern, colorful, and engaging.`;

      console.log(`Generating image for topic: "${topic}" using Pollinations.ai`);

      // Image configuration
      const width = 1024;
      const height = 1024;
      const seed = Math.floor(Math.random() * 10000); // Random seed for variation
      const model = "flux"; // Using 'flux' model

      // Construct the Pollinations.ai URL
      const imageUrl = `https://pollinations.ai/p/${encodeURIComponent(prompt)}?width=${width}&height=${height}&seed=${seed}&model=${model}`;

      console.log(`Fetching image from: ${imageUrl}`);

      // Fetch the image from Pollinations.ai
      const response = await fetch(imageUrl);

      if (!response.ok) {
        throw new Error(`Failed to fetch image: ${response.statusText}`);
      }

      // Get the image as a buffer
      const arrayBuffer = await response.arrayBuffer();
      const buffer = Buffer.from(arrayBuffer);

      // Convert to base64
      const base64Image = buffer.toString("base64");

      // Create data URI
      const dataUri = `data:image/png;base64,${base64Image}`;

      console.log("Image generated successfully!");

      return NextResponse.json({
        imageUrl: dataUri,
        imageUrlBlur: dataUri,
        attribution: {
          source: "Generated by Pollinations.ai",
        },
      });
    } catch (pollinationsError) {
      console.error("Pollinations.ai image generation error:", pollinationsError);
      // Fall through to generate a gradient background
    }

    // Fallback: Generate a gradient based on the topic's hash
    const imageUrl = generateGradientForTopic(topic);

    return NextResponse.json({
      imageUrl,
      imageUrlBlur: imageUrl,
      attribution: null,
    });
  } catch (error) {
    console.error("Error generating image:", error);
    return NextResponse.json(
      { error: "Failed to generate image" },
      { status: 500 }
    );
  }
}

// Generate a deterministic gradient based on topic
function generateGradientForTopic(topic: string): string {
  // Create a simple hash from the topic
  let hash = 0;
  for (let i = 0; i < topic.length; i++) {
    hash = (hash << 5) - hash + topic.charCodeAt(i);
    hash = hash & hash;
  }

  // Generate colors from the hash
  const hue1 = Math.abs(hash % 360);
  const hue2 = (hue1 + 60) % 360;
  const hue3 = (hue1 + 120) % 360;

  return `linear-gradient-${hue1}-${hue2}-${hue3}`;
}
