import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY || "",
});

export async function POST(request: NextRequest) {
  try {
    const { topic } = await request.json();

    if (!topic) {
      return NextResponse.json(
        { error: "Missing topic field" },
        { status: 400 }
      );
    }

    // List available models (for debugging)
    console.log("\n=== Listing available Imagen models ===");
    try {
      const modelsPager = ai.models.list();
      const modelsArray: any[] = [];
      const imageModels: any[] = [];
      
      // Iterate through the pager to collect models
      for await (const model of modelsPager) {
        modelsArray.push(model);
        console.log(`Model: ${model.name}`);
        console.log(`  Display Name: ${model.displayName || "N/A"}`);
        console.log(`  Description: ${model.description || "N/A"}`);
        console.log(`  Supported Methods: ${model.supportedGenerationMethods?.join(", ") || "N/A"}`);
        console.log("---");
        
        // Collect image generation models
        if (model.name?.includes("imagen") || 
            model.displayName?.toLowerCase().includes("image")) {
          imageModels.push(model);
        }
      }
      
      console.log(`\nFound ${modelsArray.length} total models`);
      console.log(`\nImage generation models (${imageModels.length}):`);
      imageModels.forEach((m: any) => {
        console.log(`  - ${m.name} (${m.displayName || "N/A"})`);
      });
    } catch (listError) {
      console.error("Error listing models:", listError);
    }
    console.log("=== End of model list ===\n");

    // Try to generate image using Imagen
    try {
      const prompt = `Create a beautiful, high-quality background image related to the topic: "${topic}". The image should be visually appealing, professional, and suitable as a background for a quiz application. Style: modern, colorful, and engaging.`;

      console.log(`Generating image for topic: "${topic}"`);
      
      const response = await ai.models.generateImages({
        model: "imagen-4.0-generate-001",
        prompt: prompt,
        config: {
          numberOfImages: 1,
        },
      });

      if (response.generatedImages && response.generatedImages.length > 0) {
        const generatedImage = response.generatedImages[0];
        const imageBytes = generatedImage.image.imageBytes;
        
        // Convert base64 image to data URI for browser use
        const dataUri = `data:image/png;base64,${imageBytes}`;

        console.log("Image generated successfully!");

        return NextResponse.json({
          imageUrl: dataUri,
          imageUrlBlur: dataUri,
          attribution: {
            source: "Generated by Google Imagen AI",
          },
        });
      }

      // If no image data found in response, fall through to gradient
      console.warn("No image data found in Imagen response");
    } catch (imagenError) {
      console.error("Imagen image generation error:", imagenError);
      // Fall through to generate a gradient background
    }

    // Fallback: Generate a gradient based on the topic's hash
    const imageUrl = generateGradientForTopic(topic);

    return NextResponse.json({
      imageUrl,
      imageUrlBlur: imageUrl,
      attribution: null,
    });
  } catch (error) {
    console.error("Error generating image:", error);
    return NextResponse.json(
      { error: "Failed to generate image" },
      { status: 500 }
    );
  }
}

// Generate a deterministic gradient based on topic
function generateGradientForTopic(topic: string): string {
  // Create a simple hash from the topic
  let hash = 0;
  for (let i = 0; i < topic.length; i++) {
    hash = (hash << 5) - hash + topic.charCodeAt(i);
    hash = hash & hash;
  }

  // Generate colors from the hash
  const hue1 = Math.abs(hash % 360);
  const hue2 = (hue1 + 60) % 360;
  const hue3 = (hue1 + 120) % 360;

  return `linear-gradient-${hue1}-${hue2}-${hue3}`;
}
