import { NextRequest, NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || "");

export async function POST(request: NextRequest) {
  try {
    const { topic } = await request.json();

    if (!topic) {
      return NextResponse.json(
        { error: "Missing topic field" },
        { status: 400 }
      );
    }

    // Try to generate image using Gemini's image generation
    try {
      const model = genAI.getGenerativeModel({
        model: "gemini-2.5-flash-image",
      });

      const prompt = `Create a beautiful, high-quality background image related to the topic: "${topic}". The image should be visually appealing, professional, and suitable as a background for a quiz application. Style: modern, colorful, and engaging.`;

      const result = await model.generateContent(prompt);
      const response = await result.response;

      // Extract image data from the response
      if (response.candidates && response.candidates[0]) {
        for (const part of response.candidates[0].content.parts) {
          if (part.inlineData && part.inlineData.data) {
            // Convert base64 image to data URI for browser use
            const imageBase64 = part.inlineData.data;
            const mimeType = part.inlineData.mimeType || "image/png";
            const dataUri = `data:${mimeType};base64,${imageBase64}`;

            return NextResponse.json({
              imageUrl: dataUri,
              imageUrlBlur: dataUri,
              attribution: {
                source: "Generated by Google Gemini AI",
              },
            });
          }
        }
      }

      // If no image data found in response, fall through to gradient
      console.warn("No image data found in Gemini response");
    } catch (geminiError) {
      console.error("Gemini image generation error:", geminiError);
      // Fall through to generate a gradient background
    }

    // Fallback: Generate a gradient based on the topic's hash
    const imageUrl = generateGradientForTopic(topic);

    return NextResponse.json({
      imageUrl,
      imageUrlBlur: imageUrl,
      attribution: null,
    });
  } catch (error) {
    console.error("Error generating image:", error);
    return NextResponse.json(
      { error: "Failed to generate image" },
      { status: 500 }
    );
  }
}

// Generate a deterministic gradient based on topic
function generateGradientForTopic(topic: string): string {
  // Create a simple hash from the topic
  let hash = 0;
  for (let i = 0; i < topic.length; i++) {
    hash = (hash << 5) - hash + topic.charCodeAt(i);
    hash = hash & hash;
  }

  // Generate colors from the hash
  const hue1 = Math.abs(hash % 360);
  const hue2 = (hue1 + 60) % 360;
  const hue3 = (hue1 + 120) % 360;

  return `linear-gradient-${hue1}-${hue2}-${hue3}`;
}
